#! /usr/bin/env python

from genomonSV.run import *
import argparse

####################
# top level parser
parser = argparse.ArgumentParser(prog = "GenomonSV")

parser.add_argument("--version", action = "version", version = "GenomonSV-0.1.0")

subparsers = parser.add_subparsers()

####################


####################
# GenomonSV parse
parse_parser = subparsers.add_parser("parse", 
                                     help = "Parse and cluster supporting read pairs for candidate structural variations")

parse_parser.add_argument("sampleInfoFile", metavar = "sample.yaml", type = str,
                          help = "input sample information file (yaml format)")

parse_parser.add_argument("paramInfoFile", metavar = "param.yaml", type = str,
                          help = "parameter information file (yaml format)")

parse_parser.set_defaults(func = genomonSV_parse)
####################   


####################
# GenomonSV filt
filt_parser = subparsers.add_parser("filt", 
                                     help = "Filter candidate structural variations")

filt_parser.add_argument("sampleInfoFile", metavar = "sample.yaml", type = str,
                          help = "input sample information file (yaml format)")

filt_parser.add_argument("paramInfoFile", metavar = "param.yaml", type = str,
                          help = "parameter information file (yaml format)")

filt_parser.set_defaults(func = genomonSV_filt)
####################


####################
# GenomonSV filt
filt_parser = subparsers.add_parser("merge",
                                     help = "Merge clustered junction files for filtering")

filt_parser.add_argument("controlPathInfoFile", metavar = "control.yaml", type = str,
                          help = "the pathes for clustered junction files")

filt_parser.add_argument("outputFilePath", metavar = "mergedControl.bedpe.gz", type = str,
                          help = "the pathes for merged control junction files")

filt_parser.add_argument("paramInfoFile", metavar = "param.yaml", type = str,
                          help = "parameter information file (yaml format)")
 
filt_parser.set_defaults(func = genomonSV_merge)
####################


args = parser.parse_args()

args.func(args)          
